import JSZip from 'jszip';
import { ProjectBlueprint, ProjectInput, ScreenItem } from '@/types/project';

export async function generateProjectZip(
  input: ProjectInput,
  blueprint: ProjectBlueprint
): Promise<Blob> {
  const zip = new JSZip();
  const tech = input.technology.toLowerCase();

  // 1. Root README.md
  zip.file('README.md', generateReadmeContent(input, blueprint));

  // 2. TEAM_ASSIGNMENTS.md
  zip.file('TEAM_ASSIGNMENTS.md', generateTeamAssignmentsContent(input, blueprint));

  // 3. GIT_WORKFLOW.md
  zip.file('GIT_WORKFLOW.md', generateGitWorkflowContent(blueprint));

  // Combine regular screens and AI suggested screens
  const allScreens: ScreenItem[] = [
    ...blueprint.screens,
    ...(blueprint.aiSuggestedScreens || []).map((s) => ({
      ...s,
      isAiSuggested: true,
    })),
  ];

  // 4. Framework specific file generation
  if (tech.includes('flutter')) {
    generateFlutterStructure(zip, input, allScreens);
  } else if (tech.includes('next')) {
    generateNextjsStructure(zip, input, allScreens);
  } else if (tech.includes('react native')) {
    generateReactNativeStructure(zip, input, allScreens);
  } else if (tech.includes('node')) {
    generateNodeStructure(zip, input, allScreens);
  } else {
    // Standard React / Vite
    generateReactStructure(zip, input, allScreens);
  }

  return await zip.generateAsync({ type: 'blob' });
}

function generateReactStructure(zip: JSZip, input: ProjectInput, screens: ScreenItem[]) {
  const src = zip.folder('src');
  const screensFolder = src?.folder('screens');
  src?.folder('components');
  src?.folder('navigation');
  src?.folder('services');
  src?.folder('hooks');
  src?.folder('types');

  screens.forEach((screen) => {
    const safeName = screen.name.replace(/[^a-zA-Z0-9]/g, '');
    const fileName = `${safeName}Screen.tsx`;
    screensFolder?.file(fileName, createReactScreenPlaceholder(screen));
  });

  src?.file(
    'App.tsx',
    `import React from 'react';

/**
 * Main Application Routing Skeleton
 * Project: ${input.projectName}
 * Generated by TeamForge AI
 */
export default function App() {
  return (
    <div style={{ padding: 32, fontFamily: 'sans-serif' }}>
      <h1>${input.projectName}</h1>
      <p>Project skeleton generated by TeamForge AI.</p>
      {/* Route your screen placeholders here */}
    </div>
  );
}
`
  );

  zip.file(
    'package.json',
    JSON.stringify(
      {
        name: input.projectName.toLowerCase().replace(/[^a-z0-9]/g, '-'),
        version: '0.1.0',
        private: true,
        scripts: {
          dev: 'vite',
          build: 'tsc && vite build',
          lint: 'eslint .',
        },
        dependencies: {
          react: '^18.3.1',
          'react-dom': '^18.3.1',
        },
      },
      null,
      2
    )
  );
}

function generateNextjsStructure(zip: JSZip, input: ProjectInput, screens: ScreenItem[]) {
  const src = zip.folder('src');
  const app = src?.folder('app');
  src?.folder('components');
  src?.folder('lib');
  src?.folder('types');

  app?.file(
    'page.tsx',
    `export default function HomePage() {
  return (
    <main style={{ padding: 32, fontFamily: 'sans-serif' }}>
      <h1>${input.projectName}</h1>
      <p>Next.js App Router starter generated by TeamForge AI.</p>
    </main>
  );
}
`
  );

  screens.forEach((screen) => {
    const slug = screen.name.toLowerCase().replace(/[^a-z0-9]/g, '-');
    const screenFolder = app?.folder(slug);
    screenFolder?.file('page.tsx', createNextScreenPlaceholder(screen));
  });

  zip.file(
    'package.json',
    JSON.stringify(
      {
        name: input.projectName.toLowerCase().replace(/[^a-z0-9]/g, '-'),
        version: '0.1.0',
        private: true,
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start',
        },
        dependencies: {
          next: '^14.2.15',
          react: '^18.3.1',
          'react-dom': '^18.3.1',
        },
      },
      null,
      2
    )
  );
}

function generateReactNativeStructure(zip: JSZip, input: ProjectInput, screens: ScreenItem[]) {
  const src = zip.folder('src');
  const screensFolder = src?.folder('screens');
  src?.folder('components');
  src?.folder('navigation');
  src?.folder('services');
  src?.folder('constants');

  screens.forEach((screen) => {
    const safeName = screen.name.replace(/[^a-zA-Z0-9]/g, '');
    const fileName = `${safeName}Screen.tsx`;
    screensFolder?.file(fileName, createReactNativeScreenPlaceholder(screen));
  });

  zip.file(
    'package.json',
    JSON.stringify(
      {
        name: input.projectName.toLowerCase().replace(/[^a-z0-9]/g, '-'),
        version: '0.1.0',
        private: true,
        dependencies: {
          react: '18.3.1',
          'react-native': '0.74.5',
        },
      },
      null,
      2
    )
  );
}

function generateFlutterStructure(zip: JSZip, input: ProjectInput, screens: ScreenItem[]) {
  const lib = zip.folder('lib');
  const screensFolder = lib?.folder('screens');
  lib?.folder('widgets');
  lib?.folder('models');
  lib?.folder('services');

  screens.forEach((screen) => {
    const safeName = screen.name.toLowerCase().replace(/[^a-z0-9]/g, '_');
    screensFolder?.file(`${safeName}_screen.dart`, createFlutterScreenPlaceholder(screen));
  });

  lib?.file(
    'main.dart',
    `import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '${input.projectName}',
      home: Scaffold(
        appBar: AppBar(title: const Text('${input.projectName}')),
        body: const Center(child: Text('TeamForge AI Starter')),
      ),
    );
  }
}
`
  );

  zip.file(
    'pubspec.yaml',
    `name: ${input.projectName.toLowerCase().replace(/[^a-z0-9]/g, '_')}
description: "${input.projectName} starter project."
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
`
  );
}

function generateNodeStructure(zip: JSZip, input: ProjectInput, screens: ScreenItem[]) {
  const src = zip.folder('src');
  const routesFolder = src?.folder('routes');
  src?.folder('controllers');
  src?.folder('services');
  src?.folder('middlewares');

  screens.forEach((screen) => {
    const slug = screen.name.toLowerCase().replace(/[^a-z0-9]/g, '-');
    routesFolder?.file(`${slug}.router.ts`, createNodeRoutePlaceholder(screen));
  });

  src?.file(
    'index.ts',
    `import express from 'express';

const app = express();
app.use(express.json());

const PORT = process.env.PORT || 4000;
app.listen(PORT, () => {
  console.log(\`Server running for ${input.projectName} on port \${PORT}\`);
});
`
  );
}

// -------------------------------------------------------------
// Screen Templates (Strictly EMPTY placeholders with metadata)
// -------------------------------------------------------------

function createReactScreenPlaceholder(screen: ScreenItem): string {
  const safeName = screen.name.replace(/[^a-zA-Z0-9]/g, '');
  const responsibilitiesText = screen.responsibilities.map((r) => ` * - ${r}`).join('\n');

  return `import React from 'react';

/**
 * ==============================================================
 * Screen: ${screen.name}
 * Assigned Developer: ${screen.assignedMember}
 * Priority: ${screen.priority}
 * Purpose: ${screen.purpose}
 *
 * Responsibilities:
${responsibilitiesText}
 *
 * TODO:
 * - Implement UI layout according to design system
 * - Hook up screen state management and form handlers
 * - Connect backend API endpoints and error states
 * ==============================================================
 */

export default function ${safeName}Screen() {
  return (
    <div style={{ padding: 24, border: '1px dashed #64748b', borderRadius: 8, margin: 16 }}>
      <h2>${screen.name}</h2>
      <p style={{ color: '#475569' }}>
        <strong>Assigned Developer:</strong> ${screen.assignedMember}
      </p>
      <p style={{ color: '#475569' }}>
        <strong>Purpose:</strong> ${screen.purpose}
      </p>
      <div style={{ marginTop: 16, background: '#f8fafc', padding: 12, borderRadius: 6 }}>
        <h4>TODO List:</h4>
        <ul>
          ${screen.responsibilities.map((r) => `<li>${r}</li>`).join('\n          ')}
        </ul>
      </div>
    </div>
  );
}
`;
}

function createNextScreenPlaceholder(screen: ScreenItem): string {
  const safeName = screen.name.replace(/[^a-zA-Z0-9]/g, '');
  const responsibilitiesText = screen.responsibilities.map((r) => ` * - ${r}`).join('\n');

  return `import React from 'react';

/**
 * ==============================================================
 * Screen: ${screen.name}
 * Assigned Developer: ${screen.assignedMember}
 * Priority: ${screen.priority}
 * Purpose: ${screen.purpose}
 *
 * Responsibilities:
${responsibilitiesText}
 *
 * TODO:
 * - Implement UI layout according to design system
 * - Hook up screen state management and server actions
 * - Connect backend API endpoints and loading/error states
 * ==============================================================
 */

export default function ${safeName}Page() {
  return (
    <main style={{ padding: 24, border: '1px dashed #64748b', borderRadius: 8, margin: 16 }}>
      <h2>${screen.name}</h2>
      <p style={{ color: '#475569' }}>
        <strong>Assigned Developer:</strong> ${screen.assignedMember}
      </p>
      <p style={{ color: '#475569' }}>
        <strong>Purpose:</strong> ${screen.purpose}
      </p>
      <div style={{ marginTop: 16, background: '#f8fafc', padding: 12, borderRadius: 6 }}>
        <h4>TODO List:</h4>
        <ul>
          ${screen.responsibilities.map((r) => `<li>${r}</li>`).join('\n          ')}
        </ul>
      </div>
    </main>
  );
}
`;
}

function createReactNativeScreenPlaceholder(screen: ScreenItem): string {
  const safeName = screen.name.replace(/[^a-zA-Z0-9]/g, '');
  const responsibilitiesText = screen.responsibilities.map((r) => ` * - ${r}`).join('\n');

  return `import React from 'react';
import { View, Text, StyleSheet } from 'react-native';

/**
 * ==============================================================
 * Screen: ${screen.name}
 * Assigned Developer: ${screen.assignedMember}
 * Priority: ${screen.priority}
 * Purpose: ${screen.purpose}
 *
 * Responsibilities:
${responsibilitiesText}
 *
 * TODO:
 * - Implement Native UI components
 * - Wire navigation transitions and gesture handlers
 * - Connect mobile API queries and offline caching
 * ==============================================================
 */

export default function ${safeName}Screen() {
  return (
    <View style={styles.container}>
      <Text style={styles.title}>${screen.name}</Text>
      <Text style={styles.subtitle}>Assigned: ${screen.assignedMember}</Text>
      <Text style={styles.purpose}>${screen.purpose}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, padding: 20, justifyContent: 'center' },
  title: { fontSize: 22, fontWeight: 'bold' },
  subtitle: { fontSize: 16, color: '#666', marginTop: 8 },
  purpose: { fontSize: 14, color: '#888', marginTop: 6 },
});
`;
}

function createFlutterScreenPlaceholder(screen: ScreenItem): string {
  const safeName = screen.name.replace(/[^a-zA-Z0-9]/g, '');

  return `import 'package:flutter/material.dart';

/**
 * ==============================================================
 * Screen: ${screen.name}
 * Assigned Developer: ${screen.assignedMember}
 * Priority: ${screen.priority}
 * Purpose: ${screen.purpose}
 *
 * TODO:
 * - Implement Widget tree and theme styling
 * - Connect StateNotifier / Riverpod / Bloc
 * - Handle async network states
 * ==============================================================
 */

class ${safeName}Screen extends StatelessWidget {
  const ${safeName}Screen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('${screen.name}')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('Assigned: ${screen.assignedMember}', style: Theme.of(context).textTheme.titleMedium),
            const SizedBox(height: 8),
            Text('Purpose: ${screen.purpose}'),
          ],
        ),
      ),
    );
  }
}
`;
}

function createNodeRoutePlaceholder(screen: ScreenItem): string {
  const responsibilitiesText = screen.responsibilities.map((r) => ` * - ${r}`).join('\n');

  return `import { Router } from 'express';

/**
 * ==============================================================
 * Route Module: ${screen.name}
 * Assigned Developer: ${screen.assignedMember}
 * Purpose: ${screen.purpose}
 *
 * Responsibilities:
${responsibilitiesText}
 *
 * TODO:
 * - Define request validation schema (Zod/Joi)
 * - Implement controller handlers
 * - Connect database queries & unit tests
 * ==============================================================
 */

const router = Router();

// GET / - placeholder
router.get('/', (req, res) => {
  res.json({
    screen: '${screen.name}',
    assigned: '${screen.assignedMember}',
    status: 'Scaffold placeholder ready for implementation',
  });
});

export default router;
`;
}

function generateReadmeContent(input: ProjectInput, blueprint: ProjectBlueprint): string {
  return `# ${input.projectName}

> ${blueprint.projectOverview}

## Project Details
- **Technology / Framework:** ${input.technology}
- **Team Size:** ${input.teamMembers.length} Members
- **Total Screens:** ${blueprint.screens.length + (blueprint.aiSuggestedScreens?.length || 0)}
- **Generated by:** [TeamForge AI](https://teamforge.ai)

---

## Team Workload Distribution
| Team Member | Role | Assigned Screens | Files To Work On | Workload |
|---|---|---|---|---|
${blueprint.teamAssignments
  .map(
    (t) =>
      `| **${t.member}** | ${t.role} | ${t.assignedScreens.join(', ')} | ${(t.assignedFiles || []).map((f) => `\`${f}\``).join('<br>')} | ${t.workloadPercentage || Math.round(100 / blueprint.teamAssignments.length)}% |`
  )
  .join('\n')}

---

## Core Features
${blueprint.coreFeatures.map((f, i) => `${i + 1}. **${f.title}** (${f.complexity} Complexity)\n   ${f.description}`).join('\n\n')}

---

## Screen Architecture
${blueprint.screens
  .map(
    (s, i) =>
      `### ${i + 1}. ${s.name} [${s.priority}]\n- **Owner:** ${s.assignedMember}\n- **File Location:** \`${s.assignedFile || 'src/screens/' + s.name + 'Screen.tsx'}\`\n- **Purpose:** ${s.purpose}\n- **Tasks to Complete:**\n${s.responsibilities.map((r) => `  - ${r}`).join('\n')}`
  )
  .join('\n\n')}

${
  blueprint.aiSuggestedScreens && blueprint.aiSuggestedScreens.length > 0
    ? `\n### AI Suggested Screens (Identified Missing)\n` +
      blueprint.aiSuggestedScreens
        .map(
          (s, i) =>
            `#### ${i + 1}. ${s.name} [${s.priority}]\n- **Owner:** ${s.assignedMember}\n- **File Location:** \`${s.assignedFile || 'src/screens/' + s.name + 'Screen.tsx'}\`\n- **Purpose:** ${s.purpose}\n- **Tasks:**\n${s.responsibilities.map((r) => `  - ${r}`).join('\n')}`
        )
        .join('\n\n')
    : ''
}

---

## Getting Started
1. Clone this repository.
2. Checkout your assigned feature branch (see \`GIT_WORKFLOW.md\`).
3. Locate your assigned files in the file tree (see \`TEAM_ASSIGNMENTS.md\`).
4. Review the TODO checklist at the top of your screen file and start building!
`;
}

function generateTeamAssignmentsContent(input: ProjectInput, blueprint: ProjectBlueprint): string {
  return `# Team Workload & Assigned Files: ${input.projectName}

${blueprint.teamAssignments
  .map(
    (m) => `## Developer: ${m.member} (${m.role})
**Workload Share:** ${m.workloadPercentage || Math.round(100 / blueprint.teamAssignments.length)}%

### Assigned Screens:
${m.assignedScreens.map((s) => `- ${s}`).join('\n')}

### Files You Need to Work On (from Project Structure):
${(m.assignedFiles || []).map((f) => `- \`${f}\``).join('\n')}

### What You Need To Do:
${m.responsibilities.map((r) => `- ${r}`).join('\n')}

---
`
  )
  .join('\n')}
`;
}

function generateGitWorkflowContent(blueprint: ProjectBlueprint): string {
  return `# GitHub Collaboration Strategy

## Recommended Feature Branches
${blueprint.githubPlan.branches
  .map((b) => `- \`${b.name}\` -> **${b.member}** (${b.purpose})`)
  .join('\n')}

---

## 7-Step Collaboration Lifecycle
${blueprint.githubPlan.workflowSteps
  .map(
    (s) => `### Step ${s.step}: ${s.phase} — ${s.title}
\`\`\`bash
${s.command}
\`\`\`
${s.description}
`
  )
  .join('\n')}
`;
}
